#!/bin/bash

echo "🚀 Instalando SSHPLUS..."

PASTA="/storage/emulated/0/ssh/sshplus"
REPO="https://github.com/cybecoari/sshplus.git"

if [ ! -d "$PASTA" ]; then
    echo "📥 Clonando repositório..."
    git clone $REPO $PASTA
else
    echo "📁 Já existe, atualizando..."
    cd $PASTA || exit
    git pull origin main
fi

chmod +x $PASTA/*.sh

echo "✅ Instalação concluída!"CTRL + O → Enter → CTRL + X

